blank_issues_enabled: false
contact_links:
  - name: 이메일 문의 (Private)
    url: mailto:jihun0948@naver.com
    about: 보안 / 비공개 문의는 이메일로 부탁드립니다.
  - name: Notion Knowledge Hub
    url: https://www.notion.so/My-Knowledge-Hub-27772d9f979f80569662de9c2e49399d?source=copy_link
    about: 프로젝트 배경과 학습 노트를 정리한 페이지
